server.port=8761
spring.application.name=servicio-eureka

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=eureka-server

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO