apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos-app
        image: ryuko67/godofgames-pedidos:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: JWT_SECRET
          value: "requiemElMejorJuegoDeGodOfGames2026SecretKeyParaJWT12345678901234"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/godofgames_pedidos
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Bullseye"
        - name: INVENTARIO_SERVICE_URL
          value: "http://inventario-service:8084"
          
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
spec:
  selector:
    app: pedidos
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8083
  type: ClusterIP
